### ISSUE TITLE
Missing underscores in orientation settings in README

### ISSUE THREAD

**Issue by Chris1LDN** [OlivierLDff/QtIosCMake#19]
Hi, thanks a lot for this project, it's very helpful.

I believe there's a problem in the docs in that they state ORIENTATION_LANDSCAPELEFT and ORIENTATION_LANDSCAPERIGHT when I think it should be ORIENTATION_LANDSCAPE_LEFT and ORIENTATION_LANDSCAPE_RIGHT.

I've attached a little patch that should correct this.

[docs_patch.txt](https://github.com/OlivierLDff/QtIosCMake/files/6252566/docs_patch.txt)

**Comment by OlivierLDff** [comment]
Thanks i fixed it in 200380b14e39e720dc3b18a496d82ec9fa3337b7
