### ISSUE TITLE
ITSAppUsesNonExemptEncryption set to true when ITS_ENCRYPTION_EXPORT_COMPLIANCE_CODE is absent

### ISSUE THREAD

**Issue by Chris1LDN** [OlivierLDff/QtIosCMake#20]
Hello again,

Doing a bit more work on my project and I hit another little problem. I've not set the ITS_ENCRYPTION_EXPORT_COMPLIANCE_CODE parameter, but the AddQtIosApp macro treats this as meaning "true" and outputs it to the Info.plist as:

```    <key>ITSAppUsesNonExemptEncryption</key><true/>```
```    <key>ITSEncryptionExportComplianceCode</key>```
```    <string>ARGIOS_ITS_ENCRYPTION_EXPORT_COMPLIANCE_CODE</string>```

I think the issue was the simple mistake of not putting ${} for the variable name, one that we've all made a million times! I've attached a patch. I've tested that this fixes my issue, where I need the key to be false, but I've not tested the case of it being true, but I think it's a safe change.

Thanks,
Chris

[compliance_patch.txt](https://github.com/OlivierLDff/QtIosCMake/files/6252944/compliance_patch.txt)

**Comment by OlivierLDff** [comment]
Strange that i never noticed this behavior before...
I've merged your patch d18770498e8c78ae608890432d40c0efabb63e09
Thanks!
