### ISSUE TITLE
What is proper TEAM_ID?

### ISSUE THREAD

**Issue by Dushistov** [OlivierLDff/QtIosCMake#6]
Thanks for project, sorry for may be stupid question.

Here is my working team_id:

<img width="420" alt="myteamid" src="https://user-images.githubusercontent.com/156697/81210141-24b97d80-8fda-11ea-8b35-81fb0e88829b.png">

it is register with just apple id, no payment for apple.

I try it pass "as is":
```cmake
    TEAM_ID "Evgeniy Dushistov (Personal Team)"
```
but xcode says that this unknown team id,
<img width="560" alt="unknown-teamid" src="https://user-images.githubusercontent.com/156697/81210348-6ea26380-8fda-11ea-9a22-1b60c077351c.png">
and suggest to replace with exactly the same string. I don't know what is different between:

> Evgeniy Dushistov (Personal Team)
and
> Evgeniy Dushistov (Personal Team)

and one xcode know, and another one passed via cmake is unknown.
I tried also:
2) Evgeniy Dushistov
3) Personal Team

I run (as suggested in README):
```sh
/usr/bin/env xcrun security find-identity -v -p codesigning
  1) long-hash "Apple Development: my-email@my-server (short-hash)"
     1 valid identities found
```
I try to use:
4) my-email@my-server 
5) long-hash
that also doesn't work.

So what should I pass as TEAM_ID, so I don't have to edit xcode project after each cmake rerun?
Any ideas?

**Comment by OlivierLDff** [comment]
You can find it [here](https://developer.apple.com/account/#/membership/)
So its a string made of char and int, for example JAZD7A6HD. But i think you need to pay to have a TEAM_ID in that form. Can you confirm me that?

There are some information [here](https://stackoverflow.com/questions/40664125/cmake-and-code-signing-in-xcode-8-for-ios-projects/45860228) about what you want to do.
Have you tried passing your long hash as `CODE_SIGN_IDENTITY`. Maybe what i called `TEAM_ID` (`DEVELOPMENT_TEAM` for xcode) should be optional in your case. And i should remove `set(QT_IOS_TEAM_ID "AAAAAAAA")` line 202?
Maybe `PROVISIONING_PROFILE_SPECIFIER` is missing in my script?

I will try some stuff and i'm coming back to you

**Comment by Dushistov** [comment]
>  Can you confirm me that?

I can only confirm that https://developer.apple.com/account/#/membership/ doesn't contain anything useful. There is still at least week before my company pays for developer account, so I can not compare with paid one.

> Have you tried passing your long hash as CODE_SIGN_IDENTITY

It make things worse.
Normally with TEAM_ID I always have to code to siging preference in xcode after
change in CMakeListst.txt and fix TEAM_ID, but with
CODE_SIGN_IDENTITY I got:

> Unknown name (AAAAAAAA)

and it is fixed, it is static label, not combobox, so I can not choose
another variant. If I remove CODE_SIGN_IDENTITY then  combobox comes back.

**Comment by OlivierLDff** [comment]
Ok i tried to create a recreate an account and i can't make it work.
I pushed a commit on master that allow you to specify `-DQT_IOS_CODE_SIGN_IDENTITY, -DQT_IOS_TEAM_ID and -DQT_IOS_PROVISIONING_PROFILE_SPECIFIER` when doing the cmake command.
For what i understood, TEAM_ID should be the `short-hash`. But it is only working with a paid team account. Sorry you will have to fix by hand for now in xcode.

For example with my free account i'm doing `cmake -DQT_IOS_TEAM_ID=B5955GFPMA -DQT_IOS_CODE_SIGN_IDENTITY="iPhone Developer ..` and then i'm fixing the stuff in xcode.

If you found a way to fix this don't hesite to share.

**Comment by OlivierLDff** [comment]
Good news i managed to find the team id for my free account, but i have no idea how to properly get it.
I was inpecting the xcode project file `project.pbxproj` inside `YourProject.xcodeproj` and this is where you dev TEAM_ID is written when you fix it by hand.

- Generate your project and fix the profile with xcode gui.
- Run `YourProject.xcodeproj/project.pbxproj | grep DEVELOPMENT_TEAM`

There you should see your developement TEAM_ID and some `123456789A`. Don't know why there are here.

Anyway once you have your TEAM_ID you should be able to use it for the next cmake run.

If anyone knows how to get this number properly, i'm interested.

**Comment by OlivierLDff** [comment]
I consider this issue close, feel free to reopen if more need.
