### ISSUE TITLE
Xcode: No publish dialog?

### ISSUE THREAD

**Issue by Dushistov** [OlivierLDff/QtIosCMake#7]
The problem can be reproducible with  https://github.com/davemilter/qt_ios_libs_bug (found this hello world in the closed issues).

I added:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6526704..399959b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -28,5 +28,9 @@ IF(${CMAKE_SYSTEM_NAME} STREQUAL "iOS")
     target_link_libraries(foo PRIVATE Qt5::QmlWorkerScript)
   endif()
 
-  add_qt_ios_app(foo)
+  add_qt_ios_app(foo
+    BUNDLE_IDENTIFIER "..."
+    TEAM_ID "..."
+    VERSION "1.2.3"
+    )
 ENDIF()
```
And run 

cmake -DCMAKE_PREFIX_PATH=/Users/evgeniy/Qt/5.15.0/ios -DDEPLOYMENT_TARGET=11.0 -DCMAKE_TOOLCHAIN_FILE=../IosCMakeToolchain/ios.toolchain.cmake -DPLATFORM=OS64 -DENABLE_BITCODE=FALSE -G "Xcode" ..

I used paid Apple account, and all works fine (building and running on real devices).

But then I want to publish application and can not see "publish dialog",
after I choose Product->Archive, Xcode rebuilds my project in release mode,
signing it and that's all.

I created swift "hello world" with the same team and bundle id,
and Xcode shows this after: Product->Archive

<img width="1006" alt="Screenshot 2020-06-09 at 16 44 09" src="https://user-images.githubusercontent.com/156697/84155493-0cbd9980-aa71-11ea-9838-e9b638217ac8.png">

Any idea why Xcode thinks that it is not worth to upload https://github.com/davemilter/qt_ios_libs_bug  into their shop?

**Comment by OlivierLDff** [comment]
I don't have any developper account any more, and I never try to publish to app store.
Can you reproduce the problem with my hello world app? https://github.com/OlivierLDff/QQuickStaticHelloWorld

**Comment by Dushistov** [comment]
@OlivierLDff 

I was able to solve the problem.
I added:
```
  set_target_properties(foo PROPERTIES
    XCODE_ATTRIBUTE_INSTALL_PATH "/Applications"
    )
```
and dialog appear. Thanks to https://stackoverflow.com/questions/22349922/xcodebuild-archive-generates-malformed-xcarchive-when-adding-custom-build-settin

May be add this option to AddQtIosApp.cmake by default?

**Comment by OlivierLDff** [comment]
This should be fixed in 32ff1c284a39462dcb97cb6ba61551da9cc61436
Thanks for the code.

**Comment by Dushistov** [comment]
I validate this fix little later today. I am still fighting with apple store.
I also fixed issue with `MACOSX_BUNDLE_LAUNCHSCREEN_STORYBOARD` calculation in AddQtIosApp.cmake,
and I am now fighting with icons problem. When I finally able to upload build to apple connect and revalidate all my hacks and your fix to make it possible and may be create PR.

**Comment by OlivierLDff** [comment]
For icons you can check how i did it there : https://github.com/OlivierLDff/QaterialGallery/tree/master/platform/ios

**Comment by Dushistov** [comment]
@OlivierLDff 

Thanks, I am mainly had problem with imagemagic options for writing script to generate all suitable images.
